export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_CONTENT = "SET_USER_CONTENT";
export const GET_SUCCESS_MSG = "GET_SUCCESS_MSG";
export const SET_USER_MSG = "SET_USER_MSG";
export const SET_USER_SESSION = "SET_USER_SESSION";
